services:
  db:
    image: postgres:16
    container_name: order_splitter_db
    environment:
      POSTGRES_DB: order_splitter
      POSTGRES_USER: order_splitter
      POSTGRES_PASSWORD: order_splitter
      GUNICORN_CMD_ARGS: "--timeout 180 --graceful-timeout 30 --workers 2 --threads 4"

    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: services/backend/Dockerfile
    container_name: order_splitter_backend
    environment:
      DJANGO_SETTINGS_MODULE: order_splitter.settings_backend
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DB_HOST: db
      DB_NAME: order_splitter
      DB_USER: order_splitter
      DB_PASSWORD: order_splitter
      DB_PORT: "5432"
    depends_on:
      - db

  ai:
    command: >
      gunicorn ai_service.wsgi:application
      --bind 0.0.0.0:8080
      --workers 2
      --timeout 180
      --graceful-timeout 30
    build:
      context: .
      dockerfile: services/ai/Dockerfile
    container_name: order_splitter_ai
    environment:
      DJANGO_SETTINGS_MODULE: order_splitter.settings_ai
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DB_HOST: db
      DB_NAME: order_splitter
      DB_USER: order_splitter
      DB_PASSWORD: order_splitter
      DB_PORT: "5432"
      BACKEND_URL: http://backend:8000
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    depends_on:
      - db
      - backend

  frontend:
    build:
      context: .
      dockerfile: services/frontend/Dockerfile
    container_name: order_splitter_frontend
    environment:
      DJANGO_SETTINGS_MODULE: order_splitter.settings_frontend
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DB_HOST: db
      DB_NAME: order_splitter
      DB_USER: order_splitter
      DB_PASSWORD: order_splitter
      DB_PORT: "5432"
      BACKEND_URL: http://backend:8000
    depends_on:
      - db
      - backend

  nginx:
    image: nginx:alpine
    container_name: order_splitter_nginx
    ports:
      - "8000:80"
    volumes:
      - ./services/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
      - ai

volumes:
  db_data:
