name: receipt-splitter

services:
  db:
    image: postgres:16
    container_name: receipt_splitter_db
    environment:
      POSTGRES_DB: receipt_splitter
      POSTGRES_USER: receipt_splitter
      POSTGRES_PASSWORD: receipt_splitter
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U receipt_splitter -d receipt_splitter"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    environment:
      DJANGO_SETTINGS_MODULE: order_splitter.settings_backend
      DJANGO_SECRET_KEY: dev-secret-key
      DJANGO_DEBUG: "1"
      ALLOWED_HOSTS: "*"
      AI_BASE_URL: http://ai:8080
      DB_HOST: db
      DB_NAME: receipt_splitter
      DB_USER: receipt_splitter
      DB_PASSWORD: receipt_splitter
      DB_PORT: "5432"

    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 10

    depends_on:
      db:
        condition: service_healthy

  ai:
    build:
      context: ..
      dockerfile: ai/Dockerfile
    environment:
      BACKEND_BASE_URL: http://backend:8000
      BACKEND_AI_EXECUTE_PATH: /api/ai/execute/
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    expose:
      - "8080"
    depends_on:
      backend:
        condition: service_healthy
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: order_splitter_frontend
    environment:
      DJANGO_SETTINGS_MODULE: frontend_service.settings
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      BACKEND_URL: http://backend:8000
      AI_URL: http://ai:8080
    depends_on:
      backend:
        condition: service_healthy
      ai:
        condition: service_started


  nginx:
    image: nginx:alpine
    ports:
      - "8088:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - ai
volumes:
  db_data:

  
